#!/bin/bash
# Author: He4LAN

clear
termux-setup-storage > /dev/null 2>&1 &

banner(){ 
    echo -e "
                                                                                    
    \e[32m _____     ___   \e[31m _____         _       _ _         \e[0m
    \e[32m|     |___|  _| \e[31m |     |___ ___| |_ ___| | |___ ___ \e[0m
    \e[32m| | | |_ -|  _| \e[31m |-   -|   |_ -|  _| .'| | | -_|  _|\e[0m
    \e[32m|_|_|_|___|_|   \e[31m |_____|_|_|___|_| |__,|_|_|___|_|  \e[0m
                                                    
  
    
"
        echo -e "  \e[32m[\033[31m?\e[32m]\e[32mMetasploit kurulum aracı"
	    echo ""
        echo -e '  	  \e[32m[\033[31m?\e[32m]\033[33m Author:    \e[32mHe4LAN\e[0m\e[31mV1.0\e[0m'
        echo " "
	    echo -e '     \e[32m[\033[31m?\e[32m]\033[33m My Website:    \e[32;40;4mhe4lan.org\e[0m'
	    echo -e '  	  \e[32m[\033[31m?\e[32m]\033[33m INSTAGRAM: \e[32;40;4minstagram.com/he4lan\e[0m'
	    echo -e '	  \e[32m[\033[31m?\e[32m]\033[33m GITHUB:    \e[32;40;4mgithub.com/He4LAN\e[0m'

}
banner

	    echo -e "  \e[32m[\033[31m?\e[32m]\e[33m Metasploit Kurulsun mu? \033[31m[\e[32m Y/N \033[31m]\e[0m
 
    "
		read -p $'  msf >\033[31m ' he4
    if [[ $he4 == y ||  $he4 == Y  ]]; then
        
        clear
        echo -e " \e[32m[\033[31m+\e[32m]\e[33mMEVCUT DIZIN ARANIYOR..."
        sleep 3
        echo -e " \e[32m[\033[31m+\e[32m]\e[33mMETASPLOIT KURULUYOR."
        sleep 4
        pkg install git curl wget nmap -y && chmod +x msfinstaller && ./msfinstaller --installcredentials

    elif [[ $he4 == N ||  $he4 == n  ]]; then
    
    exit

    else
        echo -e " \e[32m[\033[31m!\e[32m]\e[31m Hatalı seçim! "
        sleep 1
        ./msf
    fi